/** The flows the lab's options are grouped by (v3 P), in this order. */
export const FLOWS = ["Arrival", "Home", "RSVP", "The day", "Travel", "FAQs", "Our story", "Scene", "Theme"] as const
export type Option = { key: string; label: string; flow: (typeof FLOWS)[number]; note: string; values: [string, string][]; when?: (o: Record<string, string>) => boolean }

/**
 * Prototype switches to try with Nadia and Griffin. The first value is what ships. Grouped by the flow
 * they change; an option shows only when its flow makes it meaningful (`when`). Anything settled in
 * v3 section A is gone from here, not hidden.
 */
export const OPTIONS: Option[] = [
  { key: "arrivalhint", label: "Envelope hint", flow: "Arrival", note: "A handwritten \u201copen your invite\u201d with an arrow, placed clear of their faces, or the small \u201cTap to open\u201d pill.", values: [["note", "Handwritten arrow"], ["pill", "Pill"]] },
  { key: "envpaint", label: "Painted envelope", flow: "Arrival", note: "Nadia's painted envelope on the front (a placeholder painting until her scan is in public/art/envelope).", values: [["off", "Plain paper"], ["on", "Painted"]] },
  { key: "bleed", label: "Colour bleeds in", flow: "Arrival", note: "Painted envelope only: the pencil sketch shows first, then the colour spreads over it from a wet, ragged edge.", values: [["off", "Off"], ["on", "On"]], when: (o) => o.envpaint === "on" },
  { key: "loupe", label: "Loupe", flow: "Arrival", note: "Painted envelope only: a glass lens shows the brushwork three times over. Laptop: hover. Phones: press and hold still (moving first still pulls it open).", values: [["off", "Off"], ["on", "On"]], when: (o) => o.envpaint === "on" },
  { key: "glow", label: "Lantern light", flow: "Arrival", note: "Laptop: a warm pool of light follows the mouse over the photo, and the seal catches it. Nothing else moves.", values: [["off", "Off"], ["on", "On"]] },
  { key: "tilt", label: "Envelope tilt", flow: "Arrival", note: "Laptop: the envelope tilts a few degrees toward the mouse, like a card on a table. On by default; switch off for a still envelope.", values: [["on", "Tilts"], ["off", "Still"]] },
  { key: "peek", label: "Envelope peek on hover", flow: "Arrival", note: "Desktop only: the flap lifts and a corner of the letter shows on hover.", values: [["on", "On"], ["off", "Off"]], },
  { key: "mode", label: "Site mode (preview)", flow: "Home", note: "What the site becomes later: the invite now, the week of the wedding (The day first), or the keepsake after it. The Content tab sets it for real; this previews it.", values: [["sheet", "From the sheet"], ["invite", "Invite"], ["week-of", "Week of"], ["keepsake", "Keepsake"]] },
  { key: "inkset", label: "Ink drying", flow: "Home", note: "The first time the letter opens each visit, its lines settle from a soft blur, 40 ms apart, like ink drying.", values: [["off", "Off"], ["on", "On"]] },
  { key: "countin", label: "Days count in", flow: "Home", note: "On open, the days box counts down from three more to today\u2019s number, once a visit.", values: [["off", "Off"], ["on", "On"]] },
  { key: "underline", label: "RSVP underline", flow: "Home", note: "Before they reply: a sage line draws in under \u201cRSVP by\u201d once the letter has settled.", values: [["off", "Off"], ["on", "On"]] },
  { key: "leaves", label: "Catch a leaf", flow: "Home", note: "Now and then a maple leaf drifts past, green now and red by the wedding; tap one and it lands pressed in the letter's corner.", values: [["off", "Off"], ["on", "On"]] },
  { key: "send", label: "Sending the reply", flow: "RSVP", note: "Tap to send, or press and hold until the ink fills, like pressing the hanko. Enter always sends.", values: [["tap", "Tap"], ["hold", "Hold to stamp"]] },
  { key: "fortune", label: "Fortune", flow: "RSVP", note: "After a yes. Keyframes: the tin rocks on a set curve (now). Springs: tap the tin and it rings down on a spring, the stick rises with a little overshoot, the slip drops open and settles. Reduced motion: the slip is already open.", values: [["css", "Keyframes"], ["spring", "Springs"]] },
  { key: "postcard", label: "After sending", flow: "RSVP", note: "Draw a fortune from the omikuji box, or a postcard: Sent on the front, turn it over for Griffin's fortune on the back.", values: [["off", "Omikuji box"], ["on", "Postcard"]] },
  { key: "sheetdrag", label: "Closing the sheet (phones)", flow: "RSVP", note: "X, Esc and Back to your invite always work; this adds a grab bar to drag the sheet down.", values: [["buttons", "Buttons only"], ["drag", "Drag down too"]] },
  { key: "datestyle", label: "Date", flow: "Home", note: "Under the names: the date and place as a sage badge, or as a second display line.", values: [["badge", "Badge"], ["line", "Display line"]] },
  { key: "names", label: "Names on desktop", flow: "Home", note: "From 1024: Nadia & Griffin on two lines at 88, or on one line at 56.", values: [["two", "Two lines"], ["one", "One line"]] },
  { key: "count", label: "Countdown", flow: "Home", note: "Boxes sit inside the letter (Home stays one card) and flip only when a number changes; seconds sit in a box like the rest. The strip and tiles sit under the card.", values: [["boxes", "Boxes: days to seconds"], ["boxes-nosecs", "Boxes, no seconds"], ["days", "Days only"], ["strip", "Strip under the card"], ["tiles", "Tiles under the card"]] },
  { key: "ticks", label: "What's left, once done", flow: "Home", note: "After everything's ticked: keep the three ticked rows (a returning guest sees it's done), or hide them.", values: [["stay", "Keep"], ["hide", "Hide"]] },
  { key: "signoff", label: "Sign-off", flow: "Home", note: "\u201cWith love, N & G\u201d on Home only, or at the end of every page.", values: [["home", "Home only"], ["all", "Every page"]] },
  { key: "toggle", label: "Evening mode switch (phones)", flow: "Home", note: "Phones: in the letter's top corner (no gap at the top), or fixed in the screen corner.", values: [["card", "In the letter"], ["corner", "Screen corner"]] },
  { key: "daytick", label: "Times tick in", flow: "The day", note: "Each time on the timeline darkens and settles as the line reaches it.", values: [["off", "Off"], ["on", "On"]] },
  { key: "thread", label: "Line as a thread", flow: "The day", note: "The line trails you a little as you scroll, like a thread being pulled, and still finishes at the bottom.", values: [["off", "Scroll-linked"], ["on", "Thread"]] },
  { key: "focus", label: "Focus the stay you point at", flow: "Travel", note: "Laptop: hover one stay and the others soften to 70%. Nothing grows or moves.", values: [["off", "Off"], ["on", "On"]] },
  { key: "faq", label: "FAQ answers", flow: "FAQs", note: "One at a time everywhere now. Laptops can go back to any number open from here.", values: [["one", "One at a time"], ["many", "Any open"]] },
  { key: "getthere", label: "Getting there, first action", flow: "Travel", note: "Travel's main button and The day's link: open Google Maps directions, or Show the driver first.", values: [["maps", "Google Maps"], ["driver", "Show the driver"]] },
  { key: "letterpaper", label: "Letter in Lantern", flow: "Theme", note: "Lantern: the letter and sheets go dark with the scene, or stay cream like paper under a lamp. The envelope is always cream.", values: [["dark", "Dark"], ["cream", "Cream"]] },
  { key: "modeswitch", label: "Light and Lantern switch", flow: "Theme", note: "How the page changes mode: a circle growing from the sun or moon, or a soft cross-fade of the whole page. Either way the new photo is ready first.", values: [["circle", "Circle"], ["fade", "Cross-fade"]] },
  { key: "rise", label: "Sections rise in", flow: "Theme", note: "Below the fold, each block of the letter rises 8px and settles as it scrolls into view (600 ms, 60 ms apart). Above the fold nothing moves.", values: [["off", "Off"], ["on", "On"]] },
  { key: "dockhide", label: "Dock steps aside", flow: "Theme", note: "Phones: the dock slips away while you scroll down and comes back the moment you scroll up or stop.", values: [["off", "Off"], ["on", "On"]] },
  { key: "rowhover", label: "Row hover", flow: "Theme", note: "Whole rows (questions, ticks, places to stay, your reply) get one soft tint under the pointer, and the same tint while a finger is down, with the tick box answering too. Off: rows only underline, as before.", values: [["tint", "Tint"], ["off", "Off"]] },
  { key: "clockroll", label: "Kyoto clock rolls", flow: "The day", note: "When the Kyoto time ticks over, the new minute rolls up into place like a station board, quietly.", values: [["on", "On"], ["off", "Off"]] },
  { key: "haptics", label: "Haptic ticks", flow: "Theme", note: "Android phones: a tiny tick when the envelope opens and when the hanko lands. iPhones don\u2019t allow it, so nothing happens there.", values: [["off", "Off"], ["on", "On"]] },
  { key: "lang", label: "Language (draft)", flow: "Theme", note: "Preview the Japanese draft. Lines not translated yet stay in English; a native speaker checks it before guests can switch.", values: [["en", "English"], ["ja", "日本語"]] },
  { key: "accent", label: "Accent", flow: "Theme", note: "Green-forward (links, selected lines, text selection in forest and moss; rust stays for the button and the seal), or rust everywhere.", values: [["green", "Green"], ["rust", "Rust"]] },
  { key: "story", label: "Our story", flow: "Our story", note: "How the story reads on Our story: letter pages, a map of stops, a timeline, or a stack of cards you drag through.", values: [["b", "Map"], ["d", "Card stack"], ["a", "Letter pages"], ["c", "Timeline"]] },
  { key: "mapmode", label: "Map", flow: "Our story", note: "Map only: the journey from Brisbane and Canada to Kyoto (Figma D1), or stops along one path.", values: [["journey", "Journey to Kyoto (the Figma plan)"], ["trail", "Stops on a path"]], when: (o) => (o.story ?? "b") === "b" },
  { key: "mapdrag", label: "Map interaction", flow: "Our story", note: "Map only: tap the stops, or also drag the seal across the map and the chapters open as it passes.", values: [["tap", "Tap stops"], ["drag", "Drag the seal"]], when: (o) => (o.story ?? "b") === "b" },
  { key: "dotmap", label: "Map paper", flow: "Our story", note: "Map only: land as soft washes, or as sage dots.", values: [["off", "Washes"], ["on", "Sage dots"]], when: (o) => (o.story ?? "b") === "b" },
  { key: "hoverprint", label: "Hover prints", flow: "Our story", note: "Laptop, map only: hover a stop and a small print rises beside it, tilted, from the side you came from. Photos go on the prints once we have them.", values: [["off", "Off"], ["on", "On"]], when: (o) => (o.story ?? "b") === "b" },
  { key: "flying", label: "Flying from", flow: "Our story", note: "Map only: an optional \u201cFlying from?\u201d on Travel, shown on the map as counts, never names.", values: [["off", "Off"], ["on", "On"]], when: (o) => (o.story ?? "b") === "b" },
  { key: "photo", label: "Photo", flow: "Scene", note: "Which photo sits behind the envelope and pages: one per mode (the hill by day, the lane in Lantern), or the same one in both modes.", values: [["each", "One per mode"], ["day", "Kyoto view, both modes"], ["night", "Night lane, both modes"]] },
  { key: "scene", label: "Scene", flow: "Scene", note: "Behind the letter on every page: their photo (for now), the moving paper, Nadia's painted plates once they exist, or the December walk.", values: [["photo", "Their photo"], ["auto", "Paper"], ["plate", "Painted"], ["walk", "Walk (December)"]] },
  { key: "stamps", label: "Stamp book", flow: "Scene", note: "Walk scene only: a stamp for each page visited, in the top bar.", values: [["off", "Off"], ["on", "On"]], when: (o) => o.scene === "walk" },
  { key: "density", label: "Density", flow: "Theme", note: "Field heights and the letter's padding.", values: [["auto", "Theme"], ["compact", "Compact"], ["comfortable", "Comfortable"], ["roomy", "Roomy"]] },
  { key: "round", label: "Roundness", flow: "Theme", note: "Every control, the nav, sections and the letter together (8 / 16 / 24 scaled).", values: [["auto", "Theme"], ["sharp", "Sharp"], ["soft", "Soft"], ["round", "Round"]] },
  { key: "navtint", label: "Nav pill", flow: "Theme", note: "Laptop top bar: the current page on a sage tint with a fine sage line, and a lighter tint under the pointer. Paper: the old pale marker, no hover fill.", values: [["sage", "Sage"], ["paper", "Paper"]] },
  { key: "navigation", label: "Navigation", flow: "Theme", note: "Pages: swipe between letters on phones, the top bar on a laptop. Desk (preview, laptop): the other letters peek out from behind this one as paper tabs; click one to bring it forward.", values: [["pages", "Pages"], ["desk", "Desk (preview)"]] },
]

