// All the words on the site, in Nadia and Griffin's own wording (from the planner's Inv details tab).
// Edit here (or later, the Content tab in the data sheet) rather than inside components.
// Japanese lives in ja.ts with the same shape. Anything missing there falls back to English.

import { DATES } from "@/lib/wedding-dates"
import { fmtDay } from "@/lib/dates"

const DAY = fmtDay(DATES.ceremonyDay) // "Fri 15 Oct 2027"
const LOCK = fmtDay(DATES.changesLock)
// The one change-by line (v3 Q7): Home under the Replied pill, the success screen and the confirmation email
const CHANGE_BY = `You can change your reply until ${LOCK}.`

// The couple's names live here once. Swapping the order is this one line.
export const COUPLE = { first: "Nadia", second: "Griffin" }

// The venue for taxi drivers, in one place (Show the driver, the day sheet, Details).
export const VENUE = {
  please: "ここへお願いします",
  nameJa: "ザ・ソウドウ 東山 京都",
  addressJa: "〒605-0827 京都府京都市東山区八坂上町366",
  name: "The Sodoh Higashiyama",
}

// Fortunes after RSVP: all 大吉 (great blessing). The site data sheet's Content tab overrides these.
export const FORTUNES = [
  "Higashiyama is all hills and stone steps. Pack shoes you can walk in.",
  "Mid October days are mild and evenings cool. Bring a light layer.",
  "Many small shops and temples are cash only. Keep some yen on you.",
  "Get an IC card (ICOCA or Suica, or add one to your phone wallet) for buses and trains.",
  "Taxi doors open and close by themselves. Let them.",
  "There's no tipping in Japan. A thank you is plenty.",
  "Rain happens. Any convenience store sells a good umbrella.",
  "Send big bags ahead from the airport with a luggage delivery service.",
  "The temples near the venue are calm before 8 am.",
  "Public bins are rare. Carry a small bag for rubbish.",
  "The Haruka train runs from Kansai Airport to Kyoto Station in about 75 minutes.",
  "You will eat very well.",
]
const A = COUPLE.first
const B = COUPLE.second
const BOTH = `${A} & ${B}`

export const en = {
  meta: {
    shortTitle: `${A[0]}&${B[0]}`,
    title: `${BOTH}`,
    eyebrow: "The Super Duper Wedding Extravaganza",
    fullTitle: `Nadia Baguley and Griffin Suddaby Super Duper Wedding Extravaganza`,
  },
  nav: { home: "Home", day: "The day", travel: "Travel", faqs: "FAQs", story: "Our story", rsvp: "RSVP" },
  letter: {
    signOff: "With love, N & G",
    credit: "Site by Jehan Baguley",
    skip: "Skip to the letter",
    open: "Tap to open",
    note: "open your invite",
    openLabel: (name: string) => `Open your invitation${name ? `, ${name}` : ""}`,
    phoneTitle: "Open on your phone",
    phoneBody: "Scan to take this invite with you.",
    comingSoon: "Coming soon",
  },
  // Photo captions and alt text (the moment, not the file). Captions are placeholders until the couple writes them.
  photos: {
    "couple-kyoto-view": { alt: `${A} and ${B} smiling on a hill above Kyoto, autumn trees behind them`, caption: "Kyoto, where it all started" },
    "kyoto-night": { alt: `${A} and ${B} in a lantern-lit Kyoto lane at night`, caption: "Kyoto, where it all started" },
    "couple-night-lane-2": { alt: `${A} and ${B} in a lantern-lit lane at night`, caption: "Back in Kyoto" },
    "couple-brisbane-market": { alt: `${A} and ${B} at a market in Brisbane`, caption: "Where it all started" },
    "couple-dog-jumper": { alt: `${A} and ${B} with a dog in a jumper`, caption: "A fun one" },
    "trio-mountain-town": { alt: `${A} and ${B} with family in a mountain town`, caption: "A trip with family" },
    "torii-mist": { alt: "A red torii gate in the mist", caption: "Misty torii on the way" },
    "griffin-cedar-forest": { alt: `${B} among tall cedar trees`, caption: `${B} in the cedars` },
    "couple-osaka-castle": { alt: `${A} and ${B} in front of Osaka Castle`, caption: "If you fly into Osaka, the castle's worth a stop" },
    "yasaka-gate-shijo": { alt: "Looking down Shijo-dori from the gate of Yasaka Shrine", caption: "Looking down Shijo-dori from Yasaka Shrine, 10 minutes' walk from the venue" },
    "higashiyama-bookshop": { alt: "A quiet street and bookshop in Higashiyama", caption: "Higashiyama, the venue's neighbourhood. Kiyomizu-dera is up the hill" },
    "umbrellas-maple-rain": { alt: "Umbrellas under red maple leaves in the rain", caption: "Pack a compact umbrella, October can be wet" },
    "pontocho-lanterns": { alt: "Lanterns along Pontocho alley at night", caption: "Pontocho, ten minutes from the venue" },
    "nara-deer-moss": { alt: "A deer resting on moss in Nara", caption: "Nara is 45 minutes away. Mind your snacks" },
    "nara-deer-nuzzle": { alt: "Two deer nuzzling in Nara", caption: "We can't wait to see you" },
    "stone-lantern-maple": { alt: "A stone lantern framed by maple leaves", caption: "" },
  } as Record<string, { alt: string; caption: string }>,
  story: {
    soonBody: "Our story is on its way.",
    title: "Our story",
    prevChapter: "Previous chapter", nextChapter: "Next chapter",
    page: (n: number, of: number) => `Chapter ${n} of ${of}`,
    kyoto: "Kyoto", brisbane: "Brisbane", canada: "Canada",
    seeList: "See as a list", seeMap: "See the map", next: "Next", done: "Done",
    flyingFrom: (n: number, of: number) => `${n} of ${of} households flying in`,
  },
  stamps: {
    open: "Stamp book", title: "Stamp book", help: "A stamp for each part of the walk you've visited, and one for your reply.",
    stops: { home: "The inn", day: "The garden gate", travel: "The station", qa: "The shrine", story: "The lane" } as Record<string, string>,
    reply: "Your reply", full: "A full book. A note from us is coming here.",
  },
  flying: { cities: {} as Partial<Record<string, string>>, title: "Flying from?", hint: "Optional. We only ever show how many, never who.", thanks: "Thanks, got it.", yours: (city: string) => `Your line is drawn from ${city}.`, change: "Change" },
  journey: {
    title: "Your journey",
    map: (city: string | null) => (city ? `A small map with your line from ${city} to Kyoto` : "A small map of the way to Kyoto"),
    review: "Flying from", notSaying: "Not saying",
    onMap: "Your line's on the map", seeIt: "See the map", notPicked: "Pick where you're flying from and your line joins the map.", pick: "Pick a city",
  },
  fortune: { title: "A little fortune for the trip", draw: "Draw one", blessing: "大吉", blessingEn: "Great blessing", number: (n: number, of: number) => `No. ${n} of ${of}`, save: "Save to my phone", copied: "Copied. Paste it into your notes.", hint: "Tap the box to draw one.", hintShake: "Tap the box, or give your phone a little shake.", boxLabel: "The fortune box. Draw a fortune", drawing: "Shaking the box…", onMap: "See your line on the map" },
  driver: { label: "Taxi from Kyoto Station", fare: "Around ¥2,000, 15 to 20 minutes.", show: "Show the driver", maps: "Directions in Google Maps", mapsOpens: "opens Google Maps", english: "Please take me here", done: "Done", copy: "Copy address", copied: "Address copied" },
  countdownMore: {
    until: "until we see you in Kyoto", tomorrow: "Tomorrow", today: "Today's the day", married: "Married",
    andCounting: "and counting", localTitle: (t: string) => `That's ${t} where you are`,
    short: { months: "months", days: "days", hours: "hrs", mins: "mins", secs: "secs", years: "years" },
  },
  theme: { label: "Evening mode" },
  home: {
    pills: { replied: "Replied" },
    rsvpClosed: `Replies are closed now. If something's changed, message ${A} or ${B}.`,
    dear: (name: string) => `Dear ${name},`,
    /** The greeting's names in this language: "Sam, Alex and your plus one" */
    dearNames: (names: string[]) => (names.length > 1 ? `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}` : names[0] ?? ""),
    yourPlusOne: "your plus one",
    label: `${DAY}, Kyoto`,
    dateLine: `${DAY}, Kyoto`,
    rsvpButton: `RSVP by ${fmtDay(DATES.rsvpBy)}`,
    yourReply: "Your reply",
    todo: { who: "Who's coming", food: "Food and a song", dates: "Travel dates", datesLater: "once you've booked", done: "done", toDo: "to do" },
    greetingLine: "we're getting married in Kyoto, where it all started, and we'd love you there. Everything you need is right here.",
    daysToGo: (n: number) => `${n} days to go`,
    kyotoLine: (time: string) => `it's ${time} in Kyoto`,
    moreLabel: "More about the day",
    links: [
      { to: "/the-day", label: "The day" },
      { to: "/travel", label: "Getting there" },
      { to: "/travel#stay", label: "Where to stay" },
    ],
    rsvpBy: `RSVP by ${fmtDay(DATES.rsvpBy)}`,
    changeReply: "Change my reply",
    changeBy: CHANGE_BY,
    reseal: "Seal it again",
    week: { greeting: "it's nearly here. Everything for Friday is on The day, and the easiest way there is below. We can't wait to see you.", day: "The day", directions: "Directions in Google Maps" },
    keepsake: { badge: "Married, Fri 15 Oct 2027, Kyoto", greeting: "thank you for coming all this way and for being part of our day. We'll add photos from the day here soon.", story: "Read our story" },
  },
  day: {
    title: "The day",
    gardenAlt: "Nadia's ink drawing of the garden at The Sodoh: the pagoda above the trees and two rows of benches either side of the aisle",
    date: DAY,
    venue: "The Sodoh Higashiyama, Kyoto",
    addressLines: ["366 Yasaka Kamimachi, Higashiyama Ward", "Kyoto 605-0827, Japan"],
    howToGetThere: "How to get there",
    countdownTitle: "Counting down",
    dateLong: DAY,
    mapAlt: "A drawn map: from Kyoto Station north to Gion-Shijo, then east up the hill to The Sodoh.",
    mapStation: "Kyoto Station", mapGion: "Gion-Shijo", mapVenue: "The Sodoh",
    countdownLabel: "Counting down",
    schedule: [
      { time: "11:00", label: "Ceremony", where: "The Garden" },
      { time: "12:00", label: "Cocktail hour", where: "Until 1:00 pm" },
      { time: "13:00", label: "Reception", where: "The Terrace, until 3:30 pm" },
    ],
    japanTime: "All times are Japan time.",
    localLine: (time: string, day: string, city: string) => `${time} ${day} ${city ? `in ${city}` : "your time"}`,
    timelineLabel: "The day, in order",
    kyotoNow: (time: string) => `It's ${time} in Kyoto right now.`,
    addToCalendar: "Add to calendar",
    googleCalendar: "Google Calendar",
    calendarOpened: "Opened in a new tab. Save it there and you're set.",
    calendarSaved: "Downloaded. Open the file to add the day.",
    appleCalendar: "Apple or Outlook (.ics)",
    print: "Print the day",
    now: "Now",
    rainPlan: "If it rains, the ceremony moves inside to one of the venue's chapels.",
    venueFacts: "The Sodoh was the home of the painter Takeuchi Seihō. Its 1.4-acre garden changes colour with the seasons.",
    gettingTitleJa: "行き方",
    stay: [
      { label: "Gion and Higashiyama", good: "Walk to the venue, the prettiest streets", watch: "Pricier, crowded, hilly stone lanes", maps: "https://www.google.com/maps/search/?api=1&query=Gion+Higashiyama+Kyoto" },
      { label: "Kawaramachi and Shijo", good: "Best all-rounder: food, shops and trains", watch: "Busy, so take a taxi on the night", maps: "https://www.google.com/maps/search/?api=1&query=Kawaramachi+Shijo+Kyoto" },
      { label: "Kyoto Station", good: "Easiest arrivals and day trips", watch: "Less charm, 15 minutes by taxi", maps: "https://www.google.com/maps/search/?api=1&query=Kyoto+Station" },
    ],
    stayGood: "Good",
    stayWatch: "Keep in mind",
  },
  travel: {
    tickHint: "Tick things off as you go. Your ticks stay on this device.",
    ticked: "Done",
    items: [
      { title: "Passport", body: "Check your passport has at least 6 months left after the date you fly home. If you need to renew it, do it soon. It can take a while. Aussies don't need a visa for a short trip to Japan. We'll tell you if the entry rules change before the trip." },
      { title: "Flights", body: "Book flights as early as you can. The date's locked in, so there's no chance of missing it. Stay a few days either side if you can: we'll share ideas for things to do before and after the wedding." },
      { title: "Where to stay", body: "Book somewhere once your flights are sorted. We'll share a few hotels and Airbnbs near the venue. Japanese hotel rooms are small and simple, so plan for that. Happy to share with other guests? Go for it." },
      { title: "SIM or pocket wifi", body: "Sort out a SIM, eSIM or pocket wifi before you go. Here are a few we've heard good things about.", links: [
        { label: "Sakura Mobile", href: "https://www.sakuramobile.jp/" },
        { label: "Ninja WiFi", href: "https://ninjawifi.com/en/plan/sim" },
        { label: "Travelkon eSIM", href: "https://www.travelkon.com.au/product-category/esim/esim-asia/japan-esim/" },
      ] },
    ],
  },
  trail: {
    label: "From Kyoto Station to The Sodoh",
    station: "Kyoto Station", stationNote: "Hachijo exit, taxi rank",
    taxi: "Taxi, 15 minutes", taxiNote: "Around ¥2,000",
    venue: "The Sodoh", venueNote: "Higashiyama",
  },
  kyotoMap: {
    title: "Around the venue",
    intro: "Tap a place to see how it fits together.",
    label: "A simple map of Kyoto: Kyoto Station, Gion-Shijo Station, the Yasaka Pagoda and The Sodoh",
    notToScale: "Not to scale",
    river: "Kamo River",
    taxiRoute: "Taxi from the station",
    walkRoute: "Walk from Gion-Shijo",
    directions: "Directions from here",
    places: [
      { id: "station", name: "Kyoto Station", ja: "京都駅", body: "Where the train from the airport gets in. Taxis wait at the Hachijo exit: about 15 minutes and around ¥2,000 to the venue. Bus 206 to Higashiyama Yasui works too.", maps: "https://www.google.com/maps/dir/?api=1&origin=Kyoto+Station&destination=The+Sodoh+Higashiyama+Kyoto" },
      { id: "gion", name: "Gion-Shijo Station", ja: "祇園四条駅", body: "The nearest station. About 10 minutes on foot along old stone lanes, with a few steps.", maps: "https://www.google.com/maps/dir/?api=1&origin=Gion-Shijo+Station&destination=The+Sodoh+Higashiyama+Kyoto&travelmode=walking" },
      { id: "pagoda", name: "Yasaka Pagoda", ja: "八坂の塔", body: "The five-storey pagoda on the lane by the venue. If you can see it, you're nearly there.", maps: "https://www.google.com/maps/search/?api=1&query=Yasaka+Pagoda+Kyoto" },
      { id: "venue", name: "The Sodoh", ja: "ザ・ソウドウ", body: "The venue: 366 Yasaka Kamimachi, Higashiyama. Ceremony in the garden at 11:00 am.", maps: "https://www.google.com/maps/dir/?api=1&destination=The+Sodoh+Higashiyama+Kyoto" },
    ],
  },
  getting: {
    title: "Getting there",
    ticked: (n: number, of: number) => `${n} of ${of} ticked off`,
    tick: (what: string) => `Done: ${what}`,
    intro: "From the airport to the garden, in the order you'll need it. The easiest way on the day: a taxi from Kyoto Station, about 15 minutes and around ¥2,000.",
    rowsLabel: "Getting there, step by step",
    beforeTitle: "Before you fly",
    rows: { passport: "Passport and visas", flights: "Flights and flying in", booking: "Booking somewhere to stay", phones: "Phones, money and plugs", weather: "Weather and what to pack", medicines: "Medicines", onTheDay: "Getting around on the day" },
    stayOpens: "Opens in Maps",
    flyingTitle: "Flying in",
    flyingBody: "Osaka (Kansai, KIX) is the easiest way in. Jetstar flies direct from Brisbane in about 9 hours; from Melbourne it's one stop. The Haruka train gets you from the airport to Kyoto Station in about 75 minutes (visitor ticket around ¥2,200). The limousine bus is about ¥2,800 and easier with big bags.",
    tokyoBody: "Coming from Tokyo? The bullet train takes about 2¼ hours. Book a Nozomi a month ahead in busy weeks, and sit on the E side for Mt Fuji.",
    walkingTitle: "Walking in",
    walkingBody: "10 minutes from Gion-Shijo, along old stone lanes with a few steps. Lovely, but take a taxi in nice shoes.",
    shuttleTitle: "Heads up: the shuttle",
    shuttleBody: "The venue shuttle only runs on weekends, so it won't run on the Friday. Plan on a taxi. We'll confirm closer to the day.",
    earlyTitle: "Arriving early?",
    earlyBody: "Drop your bags at Kyoto Station (Hands Free Kyoto) and they'll be at your hotel by evening.",
    links: {
      haruka: { label: "Haruka tickets", href: "https://www.westjr.co.jp/global/en/ticket/icoca-haruka/" },
      flights: { label: "Compare flights", href: "https://www.google.com/travel/flights?q=Flights%20to%20KIX" },
      trains: { label: "Train times", href: "https://www.jrpass.com/timetable" },
      walk: { label: "Walking route", href: "https://www.google.com/maps/dir/?api=1&origin=Gion-Shijo+Station&destination=The+Sodoh+Higashiyama+Kyoto&travelmode=walking" },
      smartraveller: { label: "Check Smartraveller", href: "https://www.smartraveller.gov.au/destinations/asia/japan" },
    },
    tips: [
      "Mid October is about 23°C by day and 14°C at night, with some rainy days. Bring a light jacket, shoes that grip on stone and a compact umbrella.",
      "Cards work in most places but carry some cash. 7-Eleven and Japan Post ATMs take foreign cards. An eSIM is the easiest way to stay online. Plugs are type A, 100V.",
      "Some medicines, like codeine, need a permit in Japan. Carry your scripts and a doctor's letter.",
    ],
  },
  stay: {
    title: "Where to stay",
    intro: "Book early: mid October is busy in Kyoto. Hotels here are small and tidy, and Kyoto adds a small accommodation tax per person per night. Sharing with other guests? Go for it.",
    mapLink: "See the three areas on a map",
    mapHref: "https://www.google.com/maps/search/?api=1&query=Gion+Kawaramachi+Kyoto+Station",
  },
  qa: {
    title: "FAQs",
    items: [
      { q: "Gifts?", a: "No gifts, truly. Getting to Kyoto is a big ask already, so you being there is the present." },
      { q: "Can I bring someone?", a: `Your invite is for the people named on it. If there's room for a plus one, your reply will ask "Bringing someone?" so you can add their name. If not, it's just you. Message ${A} or ${B} if you're unsure.` },
      { q: "What should I wear?", a: "There's no dress code. Wear what makes you feel like your best self, with shoes that grip on stone." },
      { q: "What about food?", a: "Lunch is catered, and we'll set the menu a few months before. Tell us about any dietary needs in your reply." },
      { q: "What happens to my details?", a: `Your reply goes straight to ${A} and ${B} and no one else sees it. They'll delete it a few months after the wedding.` },
      { q: "Is it a traditional Japanese wedding?", a: "No, it's a relaxed garden wedding with a few Japanese touches. Nothing to learn, just come as you are." },
    ],
    onTheDay: "On the day, contact",
    contact: "Any questions at all, message either of us. We're always happy to help.",
  },
  rsvp: {
    step: (n: number, of = 3) => `Step ${n} of ${of}`,
    whoTitle: "Who's coming?",
    coming: "Coming",
    notComing: "Can't make it",
    foodTitle: "Food and a song",
    noteTitle: "Anything to tell us?",
    dietary: "Any dietary needs?",
    dietaryOptions: ["Vegetarian", "Vegan", "Gluten free", "Dairy free", "Halal", "Kosher", "Nut allergy", "Shellfish allergy", "Egg allergy", "Other"],
    dietaryPlaceholder: "Start typing, or pick from the list",
    dietaryOther: (name: string) => `Anything else for ${name}? A word or two`,
    dietaryOtherMissing: "Add a word or two so the kitchen knows.",
    dietaryEmpty: "Nothing matches. Pick Other and tell us in a word.",
    answerMissing: (name: string) => `Choose coming or can't make it for ${name}.`,
    close: "Close",
    song: "A song for the dance floor?",
    songHint: "Search by song or artist, or just type it",
    searching: "Searching…",
    addTyped: "Add this song",
    versions: (n: number) => `${n} versions`,
    hideVersions: "Hide versions",
    justType: "Not on there? Just type it",
    noMatch: (q: string) => `Nothing matched. Add "${q}" as you typed it`,
    searchError: "Search isn't working right now. Just type it in.",
    removeSong: (s: string) => `Remove ${s}`,
    songsFull: (n: number) => `${n} songs added. Remove one to change it.`,
    songsAdded: "Your songs",
    edit: (what: string) => `Edit ${what}`,
    noMessage: "No message",
    songPlaceholder: "Search for a song",
    arrival: "Arriving",
    departure: "Leaving",
    datesHint: "Not booked yet? Add these later.",
    dateRange: `Pick dates between ${fmtDay(DATES.travelFrom)} and ${fmtDay(DATES.travelTo)}.`,
    dateOrder: "Pick a leaving date on or after your arrival.",
    message: "Anything else? (optional)",
    checkTitle: "All good?",
    send: "Send our reply",
    holdSend: "Hold to send our reply",
    holdHint: "Press and hold until it fills. Enter also sends.",
    next: "Next",
    back: "Back",
    bringing: "Bringing someone?",
    plusOne: "Their name",
    plusOneName: "Your plus one",
    notSet: "not set",
    songs: "Songs",
    messageLabel: "Message",
    dates: "Dates",
    noSongs: "None yet",
    doneTitle: { all: "You're all set", none: "Thanks for letting us know", mixed: "Thanks, got it" },
    backHome: "Back to your invite",
    sentLine: `Sent. ${CHANGE_BY}`,
    updatedLine: `Updated. ${CHANGE_BY}`,
    savingQuiet: "Sending…",
    savedOffline: "Saved on this phone. It'll send when you're back online.",
    turnOver: "Turn it over for your fortune", turnBack: "Turn it back",
    changeReply: "Change my reply",
    plusOneHint: "Leave it blank if you're not sure yet.",
    offline: "You're offline. We'll send it when you're back.",
    doneBodyEmail: "We've emailed you a copy.",
    doneBodyNoEmail: "Come back here any time to change it.",
    errors: {
      closed: `Replies are closed now. Message ${A} or ${B}.`,
      busy: "We couldn't send that just now. Your answers are still here, so try again.",
      network: "We couldn't get through. Check your connection and try again.",
      not_found: `We couldn't find this invite. Message ${A} or ${B}.`,
      other: `We couldn't send that. Your answers are still here, so try again, or message ${A} or ${B}.`,
    },
    tryAgain: "Try again",
    photos: "Happy for photos with you in them to be shared with other guests",
    privacy: `Only ${A} and ${B} see your reply.`,
  },
  notFound: {
    title: "Can't find your invite?",
    body: `Your invite has its own link. Pop in your email and we'll send it again, or message ${A} or ${B}.`,
    emailLabel: "Your email",
    helper: "The one your invite went to. We'll email your link again.",
    message: `Or email ${BOTH}`,
    send: "Send my link",
    sending: "Sending…",
    sent: "If that email is on our list, your link is on its way. Check your inbox (and junk folder) in a few minutes.",
    badEmail: "That doesn't look like an email address.",
    failed: `We couldn't send that just now. Try again, or message ${A} or ${B}.`,
  },
  unknown: {
    title: "That link doesn't look right",
    body: `We couldn't find an invite for this link. Check it's the full link from your email, or message ${A} or ${B} and we'll send it again.`,
  },
  offline: {
    title: "We couldn't open your invite",
    body: "It might be your connection. Try again in a moment.",
    retry: "Try again",
  },
  loading: "Opening your invite…",
}

export type Content = typeof en
