// All the words on the site, in Nadia and Griffin's own wording (from the planner's Inv details tab).
// Edit here (or later, the Content tab in the data sheet) rather than inside components.
// Japanese lives in ja.ts with the same shape. Anything missing there falls back to English.

// The couple's names live here once. Swapping the order is this one line.
export const COUPLE = { first: "Nadia", second: "Griffin" }

// The venue for taxi drivers, in one place (Show the driver, the day sheet, Details).
export const VENUE = {
  please: "ここへお願いします",
  nameJa: "ザ・ソウドウ 東山 京都",
  addressJa: "〒605-0827 京都府京都市東山区八坂上町366",
  name: "The Sodoh Higashiyama",
}

// Fortunes after RSVP: all 大吉 (great blessing). The site data sheet's Content tab overrides these.
export const FORTUNES = [
  "Higashiyama is all hills and stone steps. Pack shoes you can walk in.",
  "Mid October days are mild and evenings cool. Bring a light layer.",
  "Many small shops and temples are cash only. Keep some yen on you.",
  "Get an IC card (ICOCA or Suica, or add one to your phone wallet) for buses and trains.",
  "Taxi doors open and close by themselves. Let them.",
  "There's no tipping in Japan. A thank you is plenty.",
  "Rain happens. Any convenience store sells a good umbrella.",
  "Send big bags ahead from the airport with a luggage delivery service.",
  "The temples near the venue are calm before 8 am.",
  "Public bins are rare. Carry a small bag for rubbish.",
  "The Haruka train runs from Kansai Airport to Kyoto Station in about 75 minutes.",
  "You will eat very well.",
]
const A = COUPLE.first
const B = COUPLE.second
const BOTH = `${A} & ${B}`

export const en = {
  meta: {
    shortTitle: `${A[0]}&${B[0]}`,
    title: `${BOTH}`,
    eyebrow: "The Super Duper Wedding Extravaganza",
    fullTitle: `Nadia Baguley and Griffin Suddaby Super Duper Wedding Extravaganza`,
  },
  nav: { home: "Home", day: "The day", travel: "Travel", faqs: "FAQs", rsvp: "RSVP" },
  letter: {
    signOff: "With love, N & G",
    credit: "Website designed by Jehan Baguley",
    skip: "Skip to the letter",
    open: "Tap to open",
    openLabel: (name: string) => `Open your invitation${name ? `, ${name}` : ""}`,
    phoneTitle: "Open on your phone",
    phoneBody: "Scan to take this invite with you.",
    comingSoon: "Coming soon",
  },
  // Photo captions and alt text (the moment, not the file). Captions are placeholders until the couple writes them.
  photos: {
    "couple-kyoto-view": { alt: `${A} and ${B} smiling on a hill above Kyoto, autumn trees behind them`, caption: "Kyoto, where it all started" },
    "kyoto-night": { alt: `${A} and ${B} in a lantern-lit Kyoto lane at night`, caption: "Kyoto, where it all started" },
    "couple-night-lane-2": { alt: `${A} and ${B} in a lantern-lit lane at night`, caption: "Back in Kyoto" },
    "couple-brisbane-market": { alt: `${A} and ${B} at a market in Brisbane`, caption: "Where it all started" },
    "couple-dog-jumper": { alt: `${A} and ${B} with a dog in a jumper`, caption: "A fun one" },
    "trio-mountain-town": { alt: `${A} and ${B} with family in a mountain town`, caption: "A trip with family" },
    "torii-mist": { alt: "A red torii gate in the mist", caption: "Misty torii on the way" },
    "griffin-cedar-forest": { alt: `${B} among tall cedar trees`, caption: `${B} in the cedars` },
    "couple-osaka-castle": { alt: `${A} and ${B} in front of Osaka Castle`, caption: "If you fly into Osaka, the castle's worth a stop" },
    "yasaka-gate-shijo": { alt: "Looking down Shijo-dori from the gate of Yasaka Shrine", caption: "Looking down Shijo-dori from Yasaka Shrine, 10 minutes' walk from the venue" },
    "higashiyama-bookshop": { alt: "A quiet street and bookshop in Higashiyama", caption: "Higashiyama, the venue's neighbourhood. Kiyomizu-dera is up the hill" },
    "umbrellas-maple-rain": { alt: "Umbrellas under red maple leaves in the rain", caption: "Pack a compact umbrella, October can be wet" },
    "pontocho-lanterns": { alt: "Lanterns along Pontocho alley at night", caption: "Pontocho, ten minutes from the venue" },
    "nara-deer-moss": { alt: "A deer resting on moss in Nara", caption: "Nara is 45 minutes away. Mind your snacks" },
    "nara-deer-nuzzle": { alt: "Two deer nuzzling in Nara", caption: "We can't wait to see you" },
    "stone-lantern-maple": { alt: "A stone lantern framed by maple leaves", caption: "" },
  } as Record<string, { alt: string; caption: string }>,
  story: {
    soonBody: "Our story, from Brisbane to Kyoto, is on its way.",
    kyoto: "Kyoto", brisbane: "Brisbane", canada: "Canada",
    seeList: "See as a list", seeMap: "See the map", next: "Next", done: "Done",
    flyingFrom: (n: number, of: number) => `${n} of ${of} households flying in`,
  },
  flying: { title: "Flying from?", hint: "Optional. We only ever show how many, never who.", thanks: "Thanks, noted." },
  sound: { on: "Sound on", off: "Sound off", label: "Sound" },
  fortune: { title: "A little fortune for the trip", draw: "Draw one", blessing: "大吉", blessingEn: "Great blessing", number: (n: number, of: number) => `No. ${n} of ${of}`, save: "Save to my phone", copied: "Copied. Paste it into your notes." },
  driver: { label: "Taxi from Kyoto Station", fare: "Around ¥2,000, 15 to 20 minutes.", show: "Show the driver", english: "Please take me here", done: "Done", copy: "Copy address", copied: "Address copied" },
  countdownMore: {
    until: "until we see you in Kyoto", tomorrow: "Tomorrow!", today: "Today's the day", married: "Married",
    andCounting: "and counting", localTitle: (t: string) => `That's ${t} where you are`,
    short: { months: "months", days: "days", hours: "hrs", mins: "mins", secs: "secs", years: "years" },
  },
  footer: { made: `Made with love for ${BOTH}`, links: "More" },
  theme: { label: "Lantern mode" },
  home: {
    greeting: (names: string) => `Hi ${names}`,
    intro:
      "To celebrate our love and start the next chapter of our story, we wanted to bring friends and families together to the place where it all started.",
    intro2:
      "We understand that the destination is a bit farther than the venue down the road, so we want to make the trip fun, easy, and memorable for all of you.",
    rsvpLabel: "Your RSVP",
    pills: { replied: "Replied", notYet: "Not yet", lock: "Changes lock 30 Apr" },
    rsvpNotDone: "Not done yet",
    rsvpDue: "Please RSVP by Mon 15 Feb 2027",
    rsvpButton: "RSVP for your household",
    rsvpDone: "You're all set",
    rsvpDoneNone: "Thanks for letting us know",
    rsvpDoneMixed: "Thanks for replying",
    youSaid: "You said",
    said: { yes: "coming", no: "can't make it", none: "no answer yet" },
    rsvpChange: "Change my RSVP",
    rsvpClosed: `Changes are closed now. If something's changed, message ${A} or ${B}.`,
    countdown: { days: "days", hours: "hours", mins: "mins" },
    kyotoTimeShort: (time: string) => `It's ${time} in Kyoto`,
    nextUp: "Next up",
    dateStack: ["15", "10", "27"],
    kyoto: "京都",
    placeLine: "Friday · The Sodoh Higashiyama · Kyoto",
    dear: (name: string) => `Dear ${name},`,
    label: "Fri 15 Oct 2027, Kyoto",
    greetingLine: "We're getting married in Kyoto, where it all started, and we'd love you to be there. Everything you need is on this letter.",
    daysToGo: (n: number) => `${n} days to go`,
    kyotoLine: (time: string) => `it's ${time} in Kyoto`,
    moreLabel: "More about the day",
    links: [
      { to: "/the-day", label: "The day" },
      { to: "/travel", label: "Getting there" },
      { to: "/travel#stay", label: "Where to stay" },
    ],
    rsvpBy: "RSVP by 15 Feb",
    changeReply: "Change my reply",
    scheduleTitle: "The day",
    scheduleMore: "Timeline, getting there and where to stay",
    countdownTitle: "Counting down",
    countdownUnits: { months: "months", days: "days", hours: "hours", mins: "mins", secs: "secs" },
    leavesNote: "The leaves turn as the day gets closer.",
    photoCaption: "Kyoto, where it all started",
  },
  day: {
    title: "The day",
    date: "Fri 15 Oct 2027",
    venue: "The Sodoh Higashiyama, Kyoto",
    address: "366 Yasaka Kamimachi, Higashiyama Ward, Kyoto 605-0827, Japan",
    addressLines: ["366 Yasaka Kamimachi, Higashiyama Ward", "Kyoto 605-0827, Japan"],
    taxiEasiest: "A taxi from Kyoto Station is easiest: about 15 minutes, around ¥2,000.",
    dressNote: "No dress code. Wear what makes you feel like your best self, with shoes that grip on stone.",
    mapAlt: "A drawn map: from Kyoto Station north to Gion-Shijo, then east up the hill to The Sodoh.",
    mapStation: "Kyoto Station", mapGion: "Gion-Shijo", mapVenue: "The Sodoh",
    detailsTab: "Details", timelineTab: "Timeline", countdownLabel: "Counting down",
    schedule: [
      { time: "11:00", label: "Ceremony", where: "The Garden" },
      { time: "12:00", label: "Cocktail hour", where: "Until 1:00 pm" },
      { time: "13:00", label: "Reception", where: "The Terrace, until 3:30 pm" },
    ],
    japanTime: "All times are Japan time.",
    timelineLabel: "The day, in order",
    kyotoNow: (time: string) => `It's ${time} in Kyoto right now.`,
    addToCalendar: "Add to calendar",
    googleCalendar: "Google Calendar",
    appleCalendar: "Apple or Outlook (.ics)",
    openMap: "Open the map",
    print: "Print the day",
    now: "Now",
    tabs: { details: "Details", timeline: "Timeline", getting: "Getting there", stay: "Stay", faq: "FAQ" },
    detailsTitle: "The details",
    dressCode: "Dress code: no specific dress code. Wear something that makes you feel like your best self, with shoes that grip on stone.",
    rainPlan: "If it rains, the ceremony moves indoors. The venue will confirm the room.",
    venueFacts: "The Sodoh was the home of the painter Takeuchi Seihō. Its 1.4-acre garden changes colour with the seasons.",
    gettingTitle: "Getting there",
    gettingTitleJa: "行き方",
    gettingIntro: "Everything to get from the airport to the garden, in the order you'll need it.",
    easyWay: "The easy way",
    route: [
      { place: "Kyoto Station", note: "Hachijo exit, taxi rank" },
      { place: "Taxi · about 15 min", note: "Around ¥2,000. Show the driver the card" },
      { place: "The Sodoh Higashiyama", note: "Venue, Higashiyama" },
    ],
    driverTitle: "Show the driver",
    handyTitle: "Handy to know",
    handy: [
      { label: "Flying in", title: "Osaka (KIX) is easiest", body: "The Haruka train gets you to Kyoto Station in about 75 minutes. Visitor ticket ¥2,200.", action: { label: "Haruka tickets", href: "https://www.westjr.co.jp/global/en/ticket/icoca-haruka/" } },
      { label: "From Tokyo", title: "Bullet train, about 2¼ hours", body: "Book a Nozomi a month ahead in busy weeks. Sit on the E side for Mt Fuji.", action: { label: "Train times", href: "https://www.jrpass.com/timetable" } },
      { label: "Walking in", title: "10 minutes from Gion-Shijo", body: "Old stone lanes and a few steps. Lovely, but take a taxi in nice shoes.", action: { label: "Walking route", href: "https://www.google.com/maps/dir/?api=1&origin=Gion-Shijo+Station&destination=The+Sodoh+Higashiyama+Kyoto&travelmode=walking" } },
    ],
    headsUpLabel: "Heads up",
    headsUpTitle: "The venue shuttle only runs on weekends",
    headsUpBody: "It won't run on Friday, so plan on a taxi. We'll confirm closer to the day.",
    earlyTitle: "Arriving early?",
    earlyBody: "Drop your bags at Kyoto Station (Hands Free Kyoto) and they'll be at your hotel by evening.",
    stayIntro: "Book early: mid-October is busy in Kyoto. Kyoto adds a small accommodation tax per person per night.",
    stay: [
      { label: "Gion and Higashiyama", good: "Walk to the venue, the prettiest streets", watch: "Pricier, crowded, hilly stone lanes" },
      { label: "Kawaramachi and Shijo", good: "Best all-rounder: food, shops and trains", watch: "Busy; take a taxi on the night" },
      { label: "Kyoto Station", good: "Easiest arrivals and day trips", watch: "Less charm, 15 minutes by taxi" },
    ],
    stayGood: "Good",
    stayWatch: "Keep in mind",
    showDriver: "For a taxi driver",
    contacts: "Phone numbers for the day: coming closer to the date.",
    mapQr: "Scan for the map",
  },
  travel: {
    title: "Before you fly",
    lead: "Check your travel information is all up to date!",
    moreTitle: "Handy to know",
    toVenue: "Getting to the venue and where to stay are on The day page.",
    more: [
      { label: "Flying in", photo: "couple-osaka-castle", body: "Osaka (Kansai, KIX) is the easiest way in. Jetstar flies direct from Brisbane in about 9 hours. From Melbourne it's one stop. Tokyo works too if you want time there first: add about 2¼ hours by bullet train.", action: { label: "Compare flights", href: "https://www.google.com/travel/flights?q=Flights%20to%20KIX" } },
      { label: "Kansai Airport to Kyoto", body: "The Haruka train takes 75 to 80 minutes (about ¥2,200 one way with the visitor ticket). The airport limousine bus is about ¥2,800 and easier with big bags.", action: { label: "Haruka tickets (JR West)", href: "https://www.westjr.co.jp/global/en/ticket/icoca-haruka/" } },
      { label: "Weather and what to pack", photo: "umbrellas-maple-rain", body: "Mid-October is about 23°C by day and 14°C at night, with some rainy days. Bring a light jacket, shoes that grip on stone and a compact umbrella." },
      { label: "Money and phones", body: "Cards work in most places but carry some cash. 7-Eleven and Japan Post ATMs take foreign cards. An eSIM is the easiest way to stay online. Plugs are type A, 100V." },
      { label: "Medicines", body: "Some medicines, like codeine, need a permit in Japan. Carry your scripts and a doctor's letter.", action: { label: "Check Smartraveller", href: "https://www.smartraveller.gov.au/destinations/asia/japan" } },
      { label: "Older relatives", body: "One or two sights a day with a proper rest works best. Staying near Kawaramachi or the station avoids hills at the hotel end." },
    ],
    tickHint: "Tick things off as you go. Your ticks stay on this device.",
    ticked: "Done",
    items: [
      { title: "Passport", body: "Please ensure your passport is valid for at least 6 months past your return date. If you need to renew your passport, please do so soon! Aussies don't need a visa for a short trip to Japan. We'll let you know if Japan's entry rules change before the trip." },
      { title: "Flights", body: "Please book flights as early as you can. The date of the wedding is locked in, so no chance of missing it! If you can, please take the opportunity to enjoy Japan while you are here. We will have suggestions for activities for several days leading up to the wedding, and encourage you to stick around for a few days after if you are able." },
      { title: "Where to stay", body: "Please book accommodation once you have your flights booked. We will collect some recommendations for hotels or Airbnbs near the venue. Please keep in mind Japanese hotels tend to be quite small and perfunctory, so factor that into your decision-making. If you would like to coordinate with other guests and share accommodation, please do so!" },
      { title: "SIM or pocket wifi", body: "Look into buying a SIM card or pocket wifi for travel! We will provide some recommendations.", links: [
        { label: "Sakura Mobile", href: "https://www.sakuramobile.jp/" },
        { label: "Ninja WiFi", href: "https://ninjawifi.com/en/plan/sim" },
        { label: "Travelkon eSIM", href: "https://www.travelkon.com.au/product-category/esim/esim-asia/japan-esim/" },
      ] },
      { title: "Getting to the venue", body: "From Kyoto Station it's about a 15 minute taxi (around ¥2,000) or bus 206." },
    ],
  },
  getting: {
    title: "Getting there",
    intro: "From the airport to the garden, in the order you'll need it. The easiest way on the day: a taxi from Kyoto Station, about 15 minutes and around ¥2,000.",
    rowsLabel: "Getting there, step by step",
    beforeTitle: "Before you fly",
    flyingTitle: "Flying in",
    flyingBody: "Osaka (Kansai, KIX) is the easiest way in. Jetstar flies direct from Brisbane in about 9 hours; from Melbourne it's one stop. The Haruka train gets you from the airport to Kyoto Station in about 75 minutes (visitor ticket around ¥2,200). The limousine bus is about ¥2,800 and easier with big bags.",
    tokyoBody: "Coming from Tokyo? The bullet train takes about 2¼ hours. Book a Nozomi a month ahead in busy weeks, and sit on the E side for Mt Fuji.",
    walkingTitle: "Walking in",
    walkingBody: "10 minutes from Gion-Shijo, along old stone lanes with a few steps. Lovely, but take a taxi in nice shoes.",
    shuttleTitle: "Heads up: the shuttle",
    shuttleBody: "The venue shuttle only runs on weekends, so it won't run on the Friday. Plan on a taxi; we'll confirm closer to the day.",
    earlyTitle: "Arriving early?",
    earlyBody: "Drop your bags at Kyoto Station (Hands Free Kyoto) and they'll be at your hotel by evening.",
    links: {
      haruka: { label: "Haruka tickets", href: "https://www.westjr.co.jp/global/en/ticket/icoca-haruka/" },
      flights: { label: "Compare flights", href: "https://www.google.com/travel/flights?q=Flights%20to%20KIX" },
      trains: { label: "Train times", href: "https://www.jrpass.com/timetable" },
      walk: { label: "Walking route", href: "https://www.google.com/maps/dir/?api=1&origin=Gion-Shijo+Station&destination=The+Sodoh+Higashiyama+Kyoto&travelmode=walking" },
      smartraveller: { label: "Check Smartraveller", href: "https://www.smartraveller.gov.au/destinations/asia/japan" },
    },
    tips: [
      "Mid October is about 23°C by day and 14°C at night, with some rainy days. Bring a light jacket, shoes that grip on stone and a compact umbrella.",
      "Cards work in most places but carry some cash. 7-Eleven and Japan Post ATMs take foreign cards. An eSIM is the easiest way to stay online. Plugs are type A, 100V.",
      "Some medicines, like codeine, need a permit in Japan. Carry your scripts and a doctor's letter.",
    ],
  },
  stay: {
    title: "Where to stay",
    intro: "Book early: mid October is busy in Kyoto. Hotels here are small and tidy, and Kyoto adds a small accommodation tax per person per night. Sharing with other guests? Go for it.",
    mapLink: "See the three areas on a map",
    mapHref: "https://www.google.com/maps/search/?api=1&query=Gion+Kawaramachi+Kyoto+Station",
  },
  qa: {
    title: "FAQs",
    items: [
      { q: "Gifts?", a: "NO GIFTS! We understand the travel is a big ask in itself, so your presence is the present!" },
      { q: "Can I bring someone?", a: `Your invite is for the people named on it. If there's room for a plus one, your reply will ask "Bringing someone?" and you can add their name. If it doesn't, it's just you, and message ${A} or ${B} if you're unsure.` },
      { q: "What should I wear?", a: "No specific dress code, wear something that makes you feel like your best self!" },
      { q: "What about food?", a: "The wedding lunch will be catered and the menu will be determined several months before the wedding. Please let us know your dietary requirements in your RSVP!" },
      { q: "What happens to my details?", a: `Your reply goes only to ${A} and ${B}, and only they can see it. No ads, no tracking, and it's all deleted 3 months after the wedding.` },
      { q: "Is it a traditional Japanese wedding?", a: "No, it's a relaxed garden wedding with a few Japanese touches. Nothing to learn, just come as you are." },
    ],
    contact: "If you have ANY questions at all please feel free to reach out to either of us at any time - we are always happy to assist whenever we can!",
  },
  rsvp: {
    step: (n: number) => `Step ${n} of 3`,
    whoTitle: "Who's coming?",
    coming: "Coming",
    notComing: "Can't make it",
    foodTitle: "Food and a song",
    noteTitle: "Anything to tell us?",
    dietary: "Any dietary needs?",
    dietaryOptions: ["Vegetarian", "Vegan", "Gluten free", "Dairy free", "Halal", "Kosher", "Nut allergy", "Shellfish allergy", "Egg allergy", "Other"],
    dietaryPlaceholder: "Start typing, or pick from the list",
    dietaryHelp: "Pick as many as you need.",
    dietaryOther: (name: string) => `Anything else for ${name}? A word or two`,
    dietaryOtherMissing: "Add a word or two so the kitchen knows.",
    dietaryEmpty: "Nothing matches. Pick Other and tell us in a word.",
    allergy: "Allergy",
    allergyLabel: (name: string) => `What is ${name} allergic to?`,
    allergyHint: "So the kitchen can plan.",
    allergens: ["Peanuts", "Tree nuts", "Shellfish", "Fish", "Egg", "Dairy", "Gluten", "Soy", "Sesame"],
    allergyOther: "Something else (optional)",
    allergyMissing: (name: string) => `Pick or type what ${name} is allergic to.`,
    answerMissing: (name: string) => `Choose coming or can't make it for ${name}.`,
    close: "Close",
    song: "A song for the dance floor?",
    songHint: "Search by song or artist, or just type it",
    searching: "Searching…",
    addTyped: "Add this song",
    justType: "Not on there? Just type it",
    noMatch: (q: string) => `No match. Add "${q}" as typed`,
    searchError: "Search isn't working right now. Add what you typed",
    removeSong: (s: string) => `Remove ${s}`,
    songsFull: (n: number) => `${n} songs added. Remove one to change it.`,
    songsAdded: "Your songs",
    edit: (what: string) => `Edit ${what}`,
    noMessage: "No message",
    songPlaceholder: "Search for a song",
    arrival: "Arriving",
    departure: "Leaving",
    datesHint: "Not booked yet? Add these later.",
    dateRange: "We're looking for dates between 1 Sep and 30 Nov 2027.",
    dateOrder: "Your leaving date is before your arriving date. Could you check them?",
    message: "Anything else? (optional)",
    checkTitle: "All good?",
    send: "Send our RSVP",
    next: "Next",
    back: "Back",
    editUntil: "You can change this until Fri 30 Apr 2027.",
    plusOne: "Bringing someone? Their name",
    plusOneName: "Your plus one",
    notSet: "not set",
    songs: "Songs",
    messageLabel: "Message",
    dates: "Dates",
    noSongs: "None yet",
    doneTitle: { all: "You're all set", none: "Thanks for letting us know", mixed: "Thanks, all saved" },
    doneLead: { all: "See you in Kyoto.", none: "We'll miss you. If plans change, you can update this any time before the cut-off.", mixed: "We've got who's coming and who can't make it." },
    updatedEyebrow: "RSVP updated",
    savedEyebrow: "RSVP saved",
    backHome: "Back to your invite",
    savedLine: "Saved. You can change it until 30 Apr.",
    savingQuiet: "Saving…",
    savedOffline: "Saved on this phone. It'll send when you're back online.",
    thanks: { all: (n: string) => `Thank you, ${n}. We can't wait to see you in Kyoto.`, mixed: (n: string) => `Thank you, ${n}. We can't wait to see who's coming in Kyoto.`, none: (n: string) => `Thank you, ${n}. We'll miss you, and we'll share photos after.` },
    changeReply: "Change my reply",
    summary: "Your reply",
    omikuji: "A little fortune",
    omikujiSoon: "Griffin is writing the fortunes. Check back closer to the day.",
    plusOneHint: "Optional. Leave blank if you're not sure yet.",
    saving: "Sending your reply…",
    stillSending: "Still sending, Kyoto's a long way away…",
    offline: "You're offline. We'll send it when you're back.",
    done: { all: "Done! See you in Kyoto.", none: "Thanks for letting us know. We'll miss you.", mixed: "Thanks, your RSVP is saved." },
    updated: { all: "Updated. See you in Kyoto.", none: "Updated. Thanks for letting us know.", mixed: "Updated. Thanks for letting us know." },
    doneBodyEmail: "We've emailed you a copy.",
    doneBodyNoEmail: "Your answers are saved. Come back here any time to change them.",
    errors: {
      closed: `Changes are closed now. Please message ${A} or ${B}.`,
      busy: "We couldn't send that just now. Your answers are kept here, so just try again.",
      network: "We couldn't reach the server. Check your connection and try again.",
      not_found: `We couldn't find this invite. Please message ${A} or ${B}.`,
      other: `We couldn't send that. Your answers are kept here, so try again, or message ${A}.`,
    },
    tryAgain: "Try again",
    photos: "Happy for photos with you in them to be shared with other guests",
    privacy: `Your reply goes only to ${A} and ${B}, and only they can see it.`,
  },
  notFound: {
    title: "Can't find your invite?",
    body: `Your invite has its own link. Pop in your email and we'll send it again, or message ${A} or ${B}.`,
    emailLabel: "Your email",
    helper: "The one your invite went to. We'll email your link again.",
    message: `Or email ${BOTH}`,
    send: "Send my link",
    sending: "Sending…",
    sent: "If that email is on our list, your link is on its way. Check your inbox (and junk folder) in a few minutes.",
    badEmail: "That doesn't look like an email address.",
    failed: `We couldn't send that just now. Please try again, or message ${A} or ${B}.`,
  },
  unknown: {
    title: "That link doesn't look right",
    body: `We couldn't find an invite for this link. Check it's the full link from your email, or message ${A} or ${B} and we'll send it again.`,
  },
  offline: {
    title: "We couldn't open your invite",
    body: "It might be your connection. Please try again in a moment.",
    retry: "Try again",
  },
  loading: "Opening your invite…",
}

export type Content = typeof en
