// All the words on the site, in Nadia and Griffin's own wording (from the planner's Inv details tab).
// Edit here (or later, the Content tab in the data sheet) rather than inside components.
// Japanese lives in ja.ts with the same shape. Anything missing there falls back to English.

export const en = {
  meta: {
    shortTitle: "N&G",
    title: "Nadia & Griffin",
    eyebrow: "The Super Duper Wedding Extravaganza",
    fullTitle: "Nadia Baguley and Griffin Suddaby Super Duper Wedding Extravaganza",
  },
  nav: { home: "Home", day: "The day", travel: "Travel", qa: "Q&A" },
  theme: { label: "Lantern mode" },
  home: {
    greeting: (names: string) => `Hi ${names}`,
    intro:
      "To celebrate our love and start the next chapter of our story, we wanted to bring friends and families together to the place where it all started.",
    intro2:
      "We understand that the destination is a bit farther than the venue down the road, so we want to make the trip fun, easy, and memorable for all of you.",
    rsvpLabel: "Your RSVP",
    rsvpNotDone: "Not done yet",
    rsvpDue: "Please RSVP by Mon 15 Feb 2027",
    rsvpButton: "RSVP for your household",
    rsvpDone: "You're all set",
    rsvpDoneNone: "Thanks for letting us know",
    rsvpDoneMixed: "Thanks for replying",
    youSaid: "You said",
    said: { yes: "coming", no: "can't make it", none: "no answer yet" },
    rsvpChange: "Change my RSVP",
    rsvpClosed: "Changes are closed now. If something's changed, message Nadia or Griffin.",
    countdown: { days: "days", hours: "hours", mins: "mins" },
    nextUp: "Next up",
  },
  day: {
    title: "The day",
    date: "Fri 15 Oct 2027",
    venue: "The Sodoh Higashiyama, Kyoto",
    address: "366 Yasaka Kamimachi, Higashiyama Ward, Kyoto 605-0827, Japan",
    schedule: [
      { time: "11:00", label: "Ceremony", where: "The Garden" },
      { time: "12:00", label: "Cocktail hour", where: "Until 1:00 pm" },
      { time: "13:00", label: "Reception", where: "The Terrace, until 3:30 pm" },
    ],
    japanTime: "All times are Japan time.",
    kyotoNow: (time: string) => `It's ${time} in Kyoto right now.`,
    addToCalendar: "Add to calendar",
    googleCalendar: "Google Calendar",
    appleCalendar: "Apple or Outlook (.ics)",
    openMap: "Open the map",
    print: "Print the day",
    addressJa: "〒605-0827 京都府京都市東山区八坂上町366",
    showDriver: "For a taxi driver",
    contacts: "Phone numbers for the day: coming closer to the date.",
    mapQr: "Scan for the map",
  },
  travel: {
    title: "Before you fly",
    lead: "Check your travel information is all up to date!",
    tickHint: "Tick things off as you go. Your ticks stay on this device.",
    ticked: "Done",
    items: [
      { title: "Passport", body: "Please ensure your passport is valid for at least 6 months past your return date. If you need to renew your passport, please do so soon! Aussies don't need a visa for a short trip to Japan. We'll let you know if Japan's entry rules change before the trip." },
      { title: "Flights", body: "Please book flights as early as you can. The date of the wedding is locked in, so no chance of missing it! If you can, please take the opportunity to enjoy Japan while you are here. We will have suggestions for activities for several days leading up to the wedding, and encourage you to stick around for a few days after if you are able." },
      { title: "Where to stay", body: "Please book accommodation once you have your flights booked. We will collect some recommendations for hotels or Airbnbs near the venue. Please keep in mind Japanese hotels tend to be quite small and perfunctory, so factor that into your decision-making. If you would like to coordinate with other guests and share accommodation, please do so!" },
      { title: "SIM or pocket wifi", body: "Look into buying a SIM card or pocket wifi for travel! We will provide some recommendations.", links: [
        { label: "Sakura Mobile", href: "https://www.sakuramobile.jp/" },
        { label: "Ninja WiFi", href: "https://ninjawifi.com/en/plan/sim" },
        { label: "Travelkon eSIM", href: "https://www.travelkon.com.au/product-category/esim/esim-asia/japan-esim/" },
      ] },
      { title: "Getting to the venue", body: "From Kyoto Station it's about a 15 minute taxi (around ¥2,000) or bus 206." },
    ],
  },
  qa: {
    title: "Q&A",
    items: [
      { q: "Gifts?", a: "NO GIFTS! We understand the travel is a big ask in itself, so your presence is the present!" },
      { q: "What should I wear?", a: "No specific dress code, wear something that makes you feel like your best self!" },
      { q: "What about food?", a: "The wedding lunch will be catered and the menu will be determined several months before the wedding. Please let us know your dietary requirements in your RSVP!" },
      { q: "What happens to my details?", a: "Your RSVP goes only to Nadia and Griffin's own Google Sheet, not a wedding website company. Only Nadia, Griffin and Jehan can see it. No ads, no tracking, and everything is deleted 3 months after the wedding." },
      { q: "Is it a traditional Japanese wedding?", a: "No, it's a relaxed garden wedding with a few Japanese touches. Nothing to learn, just come as you are." },
    ],
    contact: "If you have ANY questions at all please feel free to reach out to either of us at any time - we are always happy to assist whenever we can!",
  },
  rsvp: {
    step: (n: number) => `Step ${n} of 3`,
    whoTitle: "Who's coming?",
    coming: "Coming",
    notComing: "Can't make it",
    foodTitle: "Food and a song",
    noteTitle: "Anything to tell us?",
    dietary: "Any dietary needs?",
    dietaryOptions: ["None", "Vegetarian", "Vegan", "Gluten free", "Allergy (tell us below)"],
    song: "A song for the dance floor?",
    songHint: "Search for a song, or just type it in.",
    songPlaceholder: "Search for a song",
    arrival: "Arriving",
    departure: "Leaving",
    datesHint: "Not booked yet? Add these later.",
    dateRange: "We're looking for dates between 1 Sep and 30 Nov 2027.",
    dateOrder: "Your leaving date is before your arriving date. Could you check them?",
    message: "Anything else? (optional)",
    checkTitle: "All good?",
    send: "Send our RSVP",
    next: "Next",
    back: "Back",
    editUntil: "You can change this until Fri 30 Apr 2027.",
    plusOne: "Bringing someone? Their name",
    plusOneName: "Your plus one",
    notSet: "not set",
    songs: "Songs",
    messageLabel: "Message",
    dates: "Dates",
    noSongs: "None yet",
    doneTitle: { all: "You're all set", none: "Thanks for letting us know", mixed: "Thanks, all saved" },
    doneLead: { all: "See you in Kyoto.", none: "We'll miss you. If plans change, you can update this any time before the cut-off.", mixed: "We've got who's coming and who can't make it." },
    updatedEyebrow: "RSVP updated",
    savedEyebrow: "RSVP saved",
    backHome: "Back to your invite",
    plusOneHint: "Optional. Leave blank if you're not sure yet.",
    saving: "Sending your reply…",
    stillSending: "Still sending, Kyoto's a long way away…",
    offline: "You're offline. We'll send it when you're back.",
    done: { all: "Done! See you in Kyoto.", none: "Thanks for letting us know. We'll miss you.", mixed: "Thanks, your RSVP is saved." },
    updated: { all: "Updated. See you in Kyoto.", none: "Updated. Thanks for letting us know.", mixed: "Updated. Thanks for letting us know." },
    doneBodyEmail: "We've emailed you a copy.",
    doneBodyNoEmail: "Your answers are saved. Come back here any time to change them.",
    errors: {
      closed: "Changes are closed now. Please message Nadia or Griffin.",
      busy: "We couldn't send that just now. Your answers are kept here, so just try again.",
      network: "We couldn't reach the server. Check your connection and try again.",
      not_found: "We couldn't find this invite. Please message Nadia or Griffin.",
      other: "We couldn't send that. Your answers are kept here, so try again, or message Nadia.",
    },
    tryAgain: "Try again",
    photos: "Happy for photos with you in them to be shared with other guests",
    privacy: "Your answers go only to Nadia and Griffin's own Google Sheet. Only Nadia, Griffin and Jehan can see them, and they're deleted 3 months after the wedding.",
  },
  notFound: {
    title: "Can't find your invite?",
    body: "Your invite has its own link. Pop in your email and we'll send it again, or message Nadia or Griffin.",
    emailLabel: "Your email",
    send: "Send my link",
    sending: "Sending…",
    sent: "If that email is on our list, your link is on its way. Check your inbox (and junk folder) in a few minutes.",
    badEmail: "That doesn't look like an email address.",
    failed: "We couldn't send that just now. Please try again, or message Nadia or Griffin.",
  },
  unknown: {
    title: "That link doesn't look right",
    body: "We couldn't find an invite for this link. Check it's the full link from your email, or message Nadia or Griffin and we'll send it again.",
  },
  offline: {
    title: "We couldn't open your invite",
    body: "It might be your connection. Please try again in a moment.",
    retry: "Try again",
  },
  loading: "Opening your invite…",
}

export type Content = typeof en
