// 日本語版 · DRAFT (v3 S). Same shape as en.ts; any line not here falls back to English.
// Full draft of every line (6 Oct). Every line is still to be checked by a native speaker before guests
// can switch to it (the switch is in the crew Options panel only until then). Polite form throughout (です・ます).
// Nothing here says more than the English does: no facts added.
import type { Content } from "./en"

type DeepPartial<T> = { [K in keyof T]?: T[K] extends (...a: never[]) => unknown ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K] }

const DAY = "2027年10月15日（金）"
const RSVP_BY = "2027年2月15日（月）"
const LOCK = "2027年4月30日（金）"
const TRAVEL_FROM = "2027年9月1日（水）"
const TRAVEL_TO = "2027年11月30日（火）"
const CHANGE_BY = `${LOCK}まで、お返事は変更できます。`
const A = "ナディア"
const B = "グリフィン"
const BOTH = `${A} & ${B}`

export const ja: DeepPartial<Content> = {
  meta: { shortTitle: "N&G", title: BOTH, eyebrow: "スーパーデューパー・ウェディング・エクストラバガンザ", fullTitle: "ナディア・バグリー & グリフィン・サダビー スーパーデューパー・ウェディング・エクストラバガンザ" },
  nav: { home: "ホーム", day: "当日", travel: "アクセス", faqs: "よくある質問", story: "ふたりのこと", rsvp: "出欠のお返事" },
  letter: {
    signOff: "愛をこめて、N & G",
    credit: "サイト制作：Jehan Baguley",
    skip: "本文へ移動",
    open: "タップしてひらく",
    note: "招待状をひらいてね",
    openLabel: (name: string) => `招待状をひらく${name ? `（${name}さん）` : ""}`,
    phoneTitle: "スマホでひらく",
    phoneBody: "読み取ると、この招待状をスマホで見られます。",
    comingSoon: "近日公開",
  },
  photos: {
    "couple-kyoto-view": { alt: `京都の丘で微笑む${A}と${B}。後ろには秋の木々`, caption: "すべてが始まった京都" },
    "kyoto-night": { alt: `夜の京都、提灯の灯る小路に立つ${A}と${B}`, caption: "すべてが始まった京都" },
    "couple-night-lane-2": { alt: `夜の提灯の灯る小路に立つ${A}と${B}`, caption: "ふたたび京都へ" },
    "couple-brisbane-market": { alt: `ブリスベンの市場にいる${A}と${B}`, caption: "すべてが始まった場所" },
    "couple-dog-jumper": { alt: `セーターを着た犬と${A}と${B}`, caption: "お気に入りの一枚" },
    "trio-mountain-town": { alt: `山あいの町で家族と${A}と${B}`, caption: "家族との旅" },
    "torii-mist": { alt: "霧の中の赤い鳥居", caption: "道すがらの霧の鳥居" },
    "griffin-cedar-forest": { alt: `杉の大木の間に立つ${B}`, caption: `杉林の${B}` },
    "couple-osaka-castle": { alt: `大阪城の前に立つ${A}と${B}`, caption: "大阪に着くなら、お城も立ち寄る価値あり" },
    "yasaka-gate-shijo": { alt: "八坂神社の門から四条通を見下ろす", caption: "八坂神社から四条通を望む。会場から徒歩10分" },
    "higashiyama-bookshop": { alt: "東山の静かな通りと本屋", caption: "会場のある東山。坂を上れば清水寺" },
    "umbrellas-maple-rain": { alt: "雨の中、赤い紅葉の下の傘", caption: "折りたたみ傘をひとつ。10月は雨の日もあります" },
    "pontocho-lanterns": { alt: "夜の先斗町に並ぶ提灯", caption: "先斗町、会場から10分" },
    "nara-deer-moss": { alt: "奈良の苔の上で休む鹿", caption: "奈良は45分ほど。おやつにご注意" },
    "nara-deer-nuzzle": { alt: "奈良で寄り添う2頭の鹿", caption: "お会いできるのを楽しみにしています" },
    "stone-lantern-maple": { alt: "紅葉に囲まれた石灯籠", caption: "" },
  },
  story: {
    soonBody: "ふたりの話は、まもなく公開します。",
    title: "ふたりのこと",
    prevChapter: "前の章", nextChapter: "次の章",
    page: (n: number, of: number) => `第${n}章（全${of}章）`,
    kyoto: "京都", brisbane: "ブリスベン", canada: "カナダ",
    seeList: "リストで見る", seeMap: "地図で見る", next: "次へ", done: "閉じる",
    flyingFrom: (n: number, of: number) => `${of}組中${n}組が到着予定`,
  },
  stamps: {
    open: "スタンプ帳", title: "スタンプ帳", help: "歩いた場所ごとにスタンプがひとつ。お返事にもひとつ。",
    stops: { home: "宿", day: "庭の門", travel: "駅", qa: "神社", story: "小路" },
    reply: "お返事", full: "スタンプがそろいました。ここにふたりからのメッセージが届きます。",
  },
  flying: { title: "どちらから来られますか？", hint: "任意です。人数のみ表示し、お名前は表示しません。", thanks: "ありがとうございます。", yours: (city: string) => `${city}からの線を描きました。`, change: "変更" },
  fortune: { title: "旅のささやかなおみくじ", draw: "ひく", blessing: "大吉", blessingEn: "大吉", number: (n: number, of: number) => `第${n}番（全${of}番）`, save: "スマホに保存", copied: "コピーしました。メモに貼り付けてください。" },
  driver: { label: "京都駅からタクシーで", fare: "約2,000円、15〜20分です。", show: "運転手さんに見せる", maps: "Googleマップで道順を見る", mapsOpens: "Googleマップがひらきます", english: "Please take me here", done: "閉じる", copy: "住所をコピー", copied: "住所をコピーしました" },
  countdownMore: {
    until: "京都でお会いできる日まで", tomorrow: "いよいよ明日", today: "今日がその日です", married: "結婚しました",
    andCounting: "カウントダウン中", localTitle: (t: string) => `お住まいの地域では${t}`,
    short: { months: "か月", days: "日", hours: "時間", mins: "分", secs: "秒", years: "年" },
  },
  theme: { label: "夜のモード" },
  home: {
    pills: { replied: "返信済み" },
    rsvpClosed: `お返事の受付は終了しました。変更がある場合は、${A}か${B}までご連絡ください。`,
    dear: (name: string) => `${name}へ`,
    dearNames: (names: string[]) => names.map((n) => (n === "お連れの方" ? n : `${n}さん`)).join("、"),
    yourPlusOne: "お連れの方",
    label: `${DAY}、京都`,
    dateLine: `${DAY}、京都`,
    rsvpButton: `${RSVP_BY}までにお返事を`,
    yourReply: "お返事",
    todo: { who: "出席される方", food: "お食事と一曲", dates: "旅の日程", datesLater: "予約が済んでから", done: "済み", toDo: "まだ" },
    greetingLine: "ふたりが出会った京都で、結婚式を挙げます。ぜひお越しください。必要なことは、すべてここにあります。",
    daysToGo: (n: number) => `あと${n}日`,
    kyotoLine: (time: string) => `京都は今${time}`,
    moreLabel: "当日について",
    links: [
      { to: "/the-day", label: "当日" },
      { to: "/travel", label: "会場への行き方" },
      { to: "/travel#stay", label: "宿泊について" },
    ],
    rsvpBy: `${RSVP_BY}までにお返事を`,
    changeReply: "お返事を変更する",
    changeBy: CHANGE_BY,
    reseal: "封筒に戻す",
    week: { greeting: "いよいよ今週です。金曜日のことはすべて「当日」のページに、いちばん簡単な行き方は下にあります。お会いできるのを楽しみにしています。", day: "当日", directions: "Googleマップで道順を見る" },
    keepsake: { badge: "2027年10月15日（金）、京都にて結婚しました", greeting: "遠くまで来てくださり、私たちの一日を一緒に過ごしてくださって、ありがとうございました。当日の写真は近日ここに掲載します。", story: "ふたりのことを読む" },
  },
  day: {
    title: "当日",
    date: DAY,
    venue: "ザ・ソウドウ 東山 京都",
    addressLines: ["〒605-0827", "京都府京都市東山区八坂上町366"],
    howToGetThere: "会場への行き方",
    countdownTitle: "カウントダウン",
    dateLong: DAY,
    mapAlt: "手描きの地図：京都駅から北へ祇園四条、そこから東へ坂を上ってザ・ソウドウへ。",
    mapStation: "京都駅", mapGion: "祇園四条", mapVenue: "ザ・ソウドウ",
    countdownLabel: "カウントダウン",
    schedule: [
      { time: "11:00", label: "挙式", where: "庭園" },
      { time: "12:00", label: "カクテルアワー", where: "13:00まで" },
      { time: "13:00", label: "披露宴", where: "テラス、15:30まで" },
    ],
    japanTime: "時刻はすべて日本時間です。",
    localLine: (time: string, day: string, city: string) => `${time}（${day}）${city ? `、現地時間（${city}）` : "、お住まいの地域の時間"}`,
    timelineLabel: "当日の流れ",
    kyotoNow: (time: string) => `京都は今、${time}です。`,
    addToCalendar: "カレンダーに追加",
    googleCalendar: "Googleカレンダー",
    calendarOpened: "新しいタブでひらきました。そちらで保存すれば完了です。",
    calendarSaved: "ダウンロードしました。ファイルをひらいて追加してください。",
    appleCalendar: "AppleまたはOutlook（.ics）",
    print: "当日の予定を印刷",
    now: "現在",
    rainPlan: "雨の場合、挙式は会場内のチャペルで行います。",
    venueFacts: "ザ・ソウドウは、日本画家・竹内栖鳳の旧邸です。約1.4エーカーの庭園は、季節ごとに色を変えます。",
    gettingTitleJa: "行き方",
    stay: [
      { label: "祇園・東山", good: "会場まで徒歩圏、いちばん美しい通り", watch: "料金は高め、混雑、石畳の坂道", maps: "https://www.google.com/maps/search/?api=1&query=Gion+Higashiyama+Kyoto" },
      { label: "河原町・四条", good: "食事、買い物、電車がそろうバランス型", watch: "にぎやかなので、当日の夜はタクシーで", maps: "https://www.google.com/maps/search/?api=1&query=Kawaramachi+Shijo+Kyoto" },
      { label: "京都駅周辺", good: "到着と日帰り旅行に便利", watch: "風情は少なめ、タクシーで15分", maps: "https://www.google.com/maps/search/?api=1&query=Kyoto+Station" },
    ],
    stayGood: "良い点",
    stayWatch: "ご注意",
  },
  travel: {
    tickHint: "済んだものにチェックを。チェックはこの端末にだけ保存されます。",
    ticked: "済み",
    items: [
      { title: "パスポート", body: "帰国日から6か月以上の有効期限があるか確認してください。更新が必要なら、早めに。時間がかかることがあります。オーストラリア国籍の方は、短期の日本滞在にビザは不要です。入国のルールが変わった場合は、旅行の前にお知らせします。" },
      { title: "航空券", body: "できるだけ早めに予約を。日程は決まっているので、乗り遅れる心配はありません。できれば前後に数日滞在してください。結婚式の前後に楽しめることをご紹介します。" },
      { title: "宿泊先", body: "航空券が取れたら、宿を予約してください。会場近くのホテルやAirbnbをいくつかご紹介します。日本のホテルの部屋は小さくシンプルなので、そのつもりで。ほかのゲストと一緒に泊まるのも大歓迎です。" },
      { title: "SIMまたはポケットWi-Fi", body: "出発前に、SIM、eSIM、ポケットWi-Fiのいずれかを用意してください。評判の良いものをいくつか。", links: [
        { label: "Sakura Mobile", href: "https://www.sakuramobile.jp/" },
        { label: "Ninja WiFi", href: "https://ninjawifi.com/en/plan/sim" },
        { label: "Travelkon eSIM", href: "https://www.travelkon.com.au/product-category/esim/esim-asia/japan-esim/" },
      ] },
    ],
  },
  trail: {
    label: "京都駅からザ・ソウドウまで",
    station: "京都駅", stationNote: "八条口、タクシー乗り場",
    taxi: "タクシーで15分", taxiNote: "約2,000円",
    venue: "ザ・ソウドウ", venueNote: "東山",
  },
  getting: {
    title: "会場への行き方",
    ticked: (n: number, of: number) => `${of}項目中${n}項目 完了`,
    tick: (what: string) => `完了：${what}`,
    intro: "空港から庭園まで、必要な順にまとめました。当日いちばん簡単なのは、京都駅からのタクシーです（約15分、2,000円ほど）。",
    rowsLabel: "会場への行き方、順番に",
    beforeTitle: "出発の前に",
    rows: { passport: "パスポートとビザ", flights: "航空券と到着", booking: "宿の予約", phones: "スマホ・お金・電源", weather: "天気と持ち物", medicines: "お薬", onTheDay: "当日の移動" },
    stayOpens: "マップでひらく",
    flyingTitle: "飛行機で",
    flyingBody: "大阪（関西国際空港、KIX）がいちばん便利です。ジェットスターはブリスベンから直行で約9時間、メルボルンからは1回乗り継ぎです。空港から京都駅までは特急はるかで約75分（訪日客向け切符は約2,200円）。リムジンバスは約2,800円で、大きな荷物があるときは楽です。",
    tokyoBody: "東京から来られますか？新幹線で約2時間15分です。混み合う週は1か月前にのぞみを予約し、富士山を見るならE席側に。",
    walkingTitle: "歩いて",
    walkingBody: "祇園四条から10分、古い石畳の小路を通り、階段が少しあります。素敵な道ですが、きれいな靴ならタクシーで。",
    shuttleTitle: "ご注意：シャトルバス",
    shuttleBody: "会場のシャトルは週末のみの運行で、金曜日は走りません。タクシーの利用をお考えください。日が近づいたら改めてご案内します。",
    earlyTitle: "早めに到着される方へ",
    earlyBody: "京都駅で荷物を預ければ（Hands Free Kyoto）、夕方にはホテルに届きます。",
    links: {
      haruka: { label: "はるかの切符", href: "https://www.westjr.co.jp/global/en/ticket/icoca-haruka/" },
      flights: { label: "航空券を比較", href: "https://www.google.com/travel/flights?q=Flights%20to%20KIX" },
      trains: { label: "電車の時刻", href: "https://www.jrpass.com/timetable" },
      walk: { label: "徒歩ルート", href: "https://www.google.com/maps/dir/?api=1&origin=Gion-Shijo+Station&destination=The+Sodoh+Higashiyama+Kyoto&travelmode=walking" },
      smartraveller: { label: "Smartravellerを確認", href: "https://www.smartraveller.gov.au/destinations/asia/japan" },
    },
    tips: [
      "10月中旬は日中23度、夜14度ほどで、雨の日もあります。薄手の上着、石畳で滑らない靴、折りたたみ傘をお持ちください。",
      "カードはほとんどの場所で使えますが、現金も少し。セブンイレブンとゆうちょのATMは海外のカードが使えます。eSIMがいちばん手軽にネットにつながります。コンセントはAタイプ、100Vです。",
      "コデインなど、日本では許可が必要な薬があります。処方箋と医師の手紙をお持ちください。",
    ],
  },
  stay: {
    title: "宿泊について",
    intro: "早めの予約を。10月中旬の京都は混み合います。ホテルは小さく整っていて、京都では1人1泊ごとに少額の宿泊税がかかります。ほかのゲストと一緒に泊まるのも大歓迎です。",
    mapLink: "3つのエリアを地図で見る",
    mapHref: "https://www.google.com/maps/search/?api=1&query=Gion+Kawaramachi+Kyoto+Station",
  },
  qa: {
    title: "よくある質問",
    items: [
      { q: "ご祝儀やプレゼントは？", a: "本当に不要です。京都まで来ていただくこと自体が大変なので、お越しいただくことが何よりの贈り物です。" },
      { q: "同伴者を連れていけますか？", a: `招待状はお名前のある方へのものです。お連れの方の枠がある場合は、お返事の中で「お連れの方はいらっしゃいますか？」とお聞きしますので、お名前を追加できます。なければ、ご本人のみとなります。不明な点は${A}か${B}にご連絡ください。` },
      { q: "服装は？", a: "ドレスコードはありません。いちばん自分らしくいられる服装で。石畳で滑らない靴がおすすめです。" },
      { q: "お食事は？", a: "昼食をご用意します。メニューは数か月前に決めます。食事の制限やアレルギーは、お返事でお知らせください。" },
      { q: "個人情報はどうなりますか？", a: `お返事は${A}と${B}にだけ届き、ほかの人は見られません。結婚式の数か月後に削除します。` },
      { q: "日本の伝統的な結婚式ですか？", a: "いいえ、日本らしさを少し添えた、くつろいだガーデンウェディングです。覚えることは何もありません。そのままの姿でお越しください。" },
    ],
    onTheDay: "当日の連絡先：",
    contact: "ご不明な点があれば、どちらにでもお気軽にご連絡ください。",
  },
  rsvp: {
    step: (n: number) => `ステップ ${n}/3`,
    whoTitle: "どなたが出席されますか？",
    coming: "出席",
    notComing: "欠席",
    foodTitle: "お食事と一曲",
    noteTitle: "ほかに伝えておきたいことは？",
    dietary: "食事の制限やアレルギーはありますか？",
    dietaryOptions: ["ベジタリアン", "ヴィーガン", "グルテンフリー", "乳製品不可", "ハラール", "コーシャ", "ナッツアレルギー", "甲殻類アレルギー", "卵アレルギー", "その他"],
    dietaryPlaceholder: "入力するか、リストから選んでください",
    dietaryOther: (name: string) => `${name}さんについて、ほかにあれば一言`,
    dietaryOtherMissing: "厨房に伝わるよう、一言添えてください。",
    dietaryEmpty: "該当するものがありません。「その他」を選んで一言お書きください。",
    answerMissing: (name: string) => `${name}さんの出席・欠席を選んでください。`,
    close: "閉じる",
    song: "ダンスでかけたい一曲は？",
    songHint: "曲名かアーティスト名で検索するか、そのまま入力してください",
    searching: "検索中…",
    addTyped: "この曲を追加",
    versions: (n: number) => `${n}バージョン`,
    hideVersions: "バージョンを隠す",
    justType: "見つからない？そのまま入力を",
    noMatch: (q: string) => `見つかりませんでした。「${q}」をそのまま追加`,
    searchError: "検索が今うまく動いていません。そのまま入力してください。",
    removeSong: (s: string) => `${s}を削除`,
    songsFull: (n: number) => `${n}曲追加済みです。変更するには1曲削除してください。`,
    songsAdded: "選んだ曲",
    edit: (what: string) => `${what}を編集`,
    noMessage: "メッセージなし",
    songPlaceholder: "曲を検索",
    arrival: "到着日",
    departure: "出発日",
    datesHint: "まだ予約していなければ、あとで追加できます。",
    dateRange: `${TRAVEL_FROM}から${TRAVEL_TO}の間で選んでください。`,
    dateOrder: "出発日は到着日以降を選んでください。",
    message: "ほかに何かあれば（任意）",
    checkTitle: "これでよろしいですか？",
    send: "お返事を送る",
    holdSend: "長押しで送る",
    holdHint: "印が満ちるまで長押ししてください。Enterでも送れます。",
    next: "次へ",
    back: "戻る",
    bringing: "お連れの方はいらっしゃいますか？",
    plusOne: "お名前",
    plusOneName: "お連れの方",
    notSet: "未設定",
    songs: "曲",
    messageLabel: "メッセージ",
    dates: "日程",
    noSongs: "まだありません",
    doneTitle: { all: "準備はばっちりです", none: "ご連絡ありがとうございます", mixed: "承りました" },
    backHome: "招待状に戻る",
    sentLine: `送信しました。${CHANGE_BY}`,
    updatedLine: `更新しました。${CHANGE_BY}`,
    savingQuiet: "送信中…",
    savedOffline: "この端末に保存しました。オンラインに戻ったら送信します。",
    changeReply: "お返事を変更する",
    plusOneHint: "まだ決まっていなければ、空欄のままで大丈夫です。",
    offline: "オフラインです。接続が戻ったら送信します。",
    doneBodyEmail: "控えをメールでお送りしました。",
    doneBodyNoEmail: "変更はいつでもここからできます。",
    errors: {
      closed: `お返事の受付は終了しました。${A}か${B}にご連絡ください。`,
      busy: "今は送信できませんでした。入力内容は残っていますので、もう一度お試しください。",
      network: "接続できませんでした。通信環境を確認して、もう一度お試しください。",
      not_found: `この招待状が見つかりませんでした。${A}か${B}にご連絡ください。`,
      other: `送信できませんでした。入力内容は残っていますので、もう一度お試しいただくか、${A}か${B}にご連絡ください。`,
    },
    tryAgain: "もう一度",
    photos: "自分が写った写真を、ほかのゲストと共有してもよい",
    privacy: `お返事は、${A}と${B}だけが見ます。`,
  },
  notFound: {
    title: "招待状が見つかりませんか？",
    body: `招待状には専用のリンクがあります。メールアドレスを入力いただければ再送します。または${A}か${B}にご連絡ください。`,
    emailLabel: "メールアドレス",
    helper: "招待状が届いたアドレスです。リンクを再送します。",
    message: `または${BOTH}にメールを`,
    send: "リンクを送る",
    sending: "送信中…",
    sent: "そのアドレスがリストにあれば、リンクをお送りしました。数分後に受信箱（と迷惑メール）をご確認ください。",
    badEmail: "メールアドレスの形式が正しくないようです。",
    failed: `今は送信できませんでした。もう一度お試しいただくか、${A}か${B}にご連絡ください。`,
  },
  unknown: {
    title: "このリンクは正しくないようです",
    body: `このリンクの招待状が見つかりませんでした。メールのリンクをすべてコピーしたか確認いただくか、${A}か${B}にご連絡いただければ再送します。`,
  },
  offline: {
    title: "招待状をひらけませんでした",
    body: "通信環境のせいかもしれません。少し待ってからもう一度お試しください。",
    retry: "もう一度",
  },
  loading: "招待状をひらいています…",
}
